const LS='mystudy_support_v7_state';
const emptyState={family:{parentName:'',email:'',familyName:'Demo Family',code:'STUDY-2486'},children:[{name:'Student A',level:'Sec 1',school:'School name',streak:0,todayDone:0,todayTotal:3,weekly:0},{name:'Student B',level:'P4',school:'School name',streak:0,todayDone:0,todayTotal:3,weekly:0}],activeChild:'Student A',homework:[],exams:[],schedule:[],weekly:[],buddies:[],checkedIn:{}};
let state=load();let loginMode='parent';let activeStudentTab='dashboard';
function load(){try{return {...structuredClone(emptyState),...(JSON.parse(localStorage.getItem(LS))||{})}}catch{return structuredClone(emptyState)}}
function save(){localStorage.setItem(LS,JSON.stringify(state));renderAll()}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),1800)}
function go(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));location.hash=id;renderAll()}
window.addEventListener('hashchange',()=>go(location.hash.replace('#','')||'home'));
window.addEventListener('load',()=>go(location.hash.replace('#','')||'home'));
function switchLogin(mode){loginMode=mode;document.querySelectorAll('.small-tabs button').forEach((b,i)=>b.classList.toggle('active',(mode==='parent'&&i===0)||(mode==='student'&&i===1)));document.getElementById('parentLoginForm').classList.toggle('hidden',mode!=='parent');document.getElementById('studentLoginForm').classList.toggle('hidden',mode!=='student')}
function createFamily(){const p=document.getElementById('signupParent').value.trim();const e=document.getElementById('signupEmail').value.trim();const f=document.getElementById('signupFamily').value.trim();state.family={parentName:p||'Parent',email:e||'parent@example.com',familyName:f||'Family',code:'STUDY-'+Math.floor(1000+Math.random()*8999)};save();toast('Family account created');go('parent')}
function parentLogin(){toast('Prototype login successful');go('parent')}
function studentJoin(){const name=document.getElementById('studentName').value.trim()||state.activeChild;const child=state.children.find(c=>c.name.toLowerCase()===name.toLowerCase())||state.children[0];state.activeChild=child.name;save();toast('Student joined');go('student')}
function renderAll(){renderParent();renderStudent();}
function renderParent(){document.getElementById('familyCode')&&(document.getElementById('familyCode').textContent='Family Code: '+state.family.code);const list=document.getElementById('childrenList');if(list){list.innerHTML=state.children.map(c=>`<article class="card child-card"><span class="badge">${c.level||'Level'}</span><h3>${c.name}</h3><p>${c.school||'School name'}</p><p><b>Streak</b> 🔥 ${c.streak||0} days <span class="pill">${c.weekly||0}%</span></p><div class="progress"><span style="width:${c.weekly||0}%"></span></div><p>Today: ${c.todayDone||0}/${c.todayTotal||3} tasks done</p><button onclick="selectChild('${c.name}');go('student')">Open dashboard</button></article>`).join('')}}
function selectChild(name){state.activeChild=name;save()}
function openAddChild(){showModal(`<p class="eyebrow">ADD CHILD</p><h2>Add a child profile</h2><label>Child name</label><input id="newChildName" placeholder="Student name"><label>Level</label><input id="newChildLevel" placeholder="e.g. Sec 1"><label>School</label><input id="newChildSchool" placeholder="School name"><button class="primary full" onclick="addChild()">Add child</button>`)}
function addChild(){const n=document.getElementById('newChildName').value.trim();if(!n)return toast('Add a name first');state.children.push({name:n,level:document.getElementById('newChildLevel').value.trim(),school:document.getElementById('newChildSchool').value.trim(),streak:0,todayDone:0,todayTotal:3,weekly:0});state.activeChild=n;closeModal();save();toast('Child added')}
function studentTab(tab){activeStudentTab=tab;document.querySelectorAll('.student-nav button').forEach(b=>b.classList.toggle('active',b.textContent.toLowerCase().includes(tab==='exam'?'exam':tab)));document.querySelectorAll('.student-panel').forEach(p=>p.classList.remove('active'));document.getElementById('student'+tab.charAt(0).toUpperCase()+tab.slice(1))?.classList.add('active')}
function child(){return state.children.find(c=>c.name===state.activeChild)||state.children[0]}
function renderStudent(){const c=child();if(!c)return;document.getElementById('studentGreeting')&&(document.getElementById('studentGreeting').textContent=`Hi ${c.name} 👋`);document.getElementById('streakStat')&&(document.getElementById('streakStat').textContent=`🔥 ${c.streak||0} days`);document.getElementById('progressStreak')&&(document.getElementById('progressStreak').textContent=`${c.streak||0} days`);renderTasks();renderFamilyProgress();renderHomework();renderExam();renderSchedule();renderWeekly();renderBuddies();const pct=progressPct();document.getElementById('hwProgress')&&(document.getElementById('hwProgress').textContent=pct.homework+'%');document.getElementById('wkProgress')&&(document.getElementById('wkProgress').textContent=pct.weekly+'%')}
function renderTasks(){const list=document.getElementById('todayTasks');if(!list)return;const due=state.homework.filter(h=>h.child===state.activeChild&&!h.done).slice(0,2);const tasks=[...due.map(h=>h.title),'Complete one homework task','Do one short revision round'].slice(0,3);list.innerHTML=tasks.map(t=>`<div class="task-row"><input type="checkbox"><b>${t}</b></div>`).join('');const nd=document.getElementById('nextDeadline');if(nd){const e=state.exams.find(x=>x.child===state.activeChild&&!x.done);nd.innerHTML=e?`<b>${e.date}</b><p>${e.subject} · ${e.title}</p>`:'No exam schedule uploaded yet.'}const sch=document.getElementById('todaySchedule');if(sch){const s=state.schedule.filter(x=>x.child===state.activeChild).slice(0,3);sch.innerHTML=s.length?s.map(x=>`<p><b>${x.date}</b> · ${x.title}</p>`).join(''):'No timetable uploaded yet.'}}
function renderFamilyProgress(){const el=document.getElementById('familyProgress');if(!el)return;el.innerHTML=state.children.map(c=>`<div class="progress-row"><b>${c.name}</b><div class="progress"><span style="width:${c.weekly||0}%"></span></div><span>${c.weekly||0}% · 🔥 ${c.streak||0}</span></div>`).join('')}
function renderHomework(){const el=document.getElementById('homeworkList');if(!el)return;const items=state.homework.filter(h=>h.child===state.activeChild);el.innerHTML=items.length?items.map((h,i)=>`<div class="card"><h3>${h.subject}: ${h.title}</h3><p class="muted">Due ${h.date} · ${h.done?'Done':'Pending'}</p>${h.proof?`<p><b>Proof:</b> ${h.proof}</p>`:''}<button onclick="completeHomework(${i})">${h.done?'Completed':'Complete with proof'}</button></div>`).join(''):'<div class="empty-box">No homework yet. Add daily homework after school.</div>'}
function openHomeworkModal(){showModal(`<p class="eyebrow">ADD HOMEWORK</p><h2>Add daily homework</h2><label>Subject</label><input id="hwSubject" placeholder="Math"><label>Homework details</label><input id="hwTitle" placeholder="Worksheet Q1-Q8"><label>Due date</label><input id="hwDate" placeholder="Tomorrow · 8 Jul"><button class="primary full" onclick="addHomework()">Add homework</button>`)}
function addHomework(){state.homework.push({child:state.activeChild,subject:val('hwSubject')||'Subject',title:val('hwTitle')||'Homework task',date:val('hwDate')||'Tomorrow',done:false});closeModal();save();toast('Homework added')}
function completeHomework(i){const items=state.homework.filter(h=>h.child===state.activeChild);const item=items[i];if(!item||item.done)return;const proof=prompt('Proof after completion?'); if(!proof)return;item.done=true;item.proof=proof;item.completedAt=new Date().toLocaleString();const c=child();c.todayDone=(c.todayDone||0)+1;c.weekly=Math.min(100,(c.weekly||0)+8);save();toast('Homework completed')}
function renderExam(){const el=document.getElementById('examList');if(!el)return;const items=state.exams.filter(x=>x.child===state.activeChild);el.className='stack';el.innerHTML=items.length?items.map((x,i)=>`<div class="card"><h3>${x.date} · ${x.subject}</h3><p>${x.title}</p><button onclick="completeExam(${i})">${x.done?'Done':'Mark done'}</button></div>`).join(''):'<div class="empty-box">No exam schedule uploaded yet.</div>'}
function completeExam(i){const items=state.exams.filter(x=>x.child===state.activeChild);const item=items[i];if(!item)return;item.done=true;save();toast('Exam task completed')}
function renderSchedule(){const el=document.getElementById('scheduleList');if(!el)return;const items=state.schedule.filter(x=>x.child===state.activeChild);el.className='stack';el.innerHTML=items.length?items.map(x=>`<div class="card"><h3>${x.date}</h3><p>${x.title}</p></div>`).join(''):'<div class="empty-box">No timetable or activities yet. Upload a timetable or add activities.</div>'}
function renderWeekly(){const el=document.getElementById('weeklyList');if(!el)return;const items=state.weekly.filter(x=>x.child===state.activeChild);el.innerHTML=items.length?items.map((x,i)=>`<div class="card"><h3>${x.title}</h3><p>${x.type||'Plan'} · ${x.date||'This week'}</p><button onclick="completeWeekly(${i})">${x.done?'Done':'Complete'}</button></div>`).join(''):'<div class="empty-box">No weekly plans yet. Add longer plans, projects or activities.</div>'}
function addWeeklyPlan(){const title=prompt('Weekly plan or reminder?');if(!title)return;state.weekly.push({child:state.activeChild,title,type:'Plan',date:'This week',done:false});save()}
function completeWeekly(i){const items=state.weekly.filter(x=>x.child===state.activeChild);if(items[i])items[i].done=true;child().weekly=Math.min(100,(child().weekly||0)+5);save();toast('Plan completed')}
function openImport(type){const labels={exam:'Import exam / WA schedule',timetable:'Import school timetable',activity:'Add tuition / activity'};showModal(`<p class="eyebrow">SETUP</p><h2>${labels[type]}</h2><p class="muted">Prototype: paste or manually enter items. A full version can parse PDF/image, then ask parent to review before import.</p><label>Item title</label><input id="impTitle" placeholder="e.g. Math WA / Monday tuition"><label>Date / time</label><input id="impDate" placeholder="e.g. Fri, 10 Jul / Tuesdays 5pm"><label>Subject / category</label><input id="impSubject" placeholder="e.g. Math"><button class="primary full" onclick="saveImport('${type}')">Save item</button>`)}
function saveImport(type){const item={child:state.activeChild,title:val('impTitle')||'Item',date:val('impDate')||'Date',subject:val('impSubject')||'General',done:false}; if(type==='exam')state.exams.push(item); else state.schedule.push(item); closeModal(); save(); toast('Saved')}
function addBuddy(){const n=val('buddyName');const s=Number(val('buddyStreak'))||0;if(!n)return;state.buddies.push({name:n,streak:s,progress:Math.min(100,s*8)});save();toast('Buddy added')}
function renderBuddies(){const el=document.getElementById('buddyList');if(!el)return;el.innerHTML=state.buddies.length?state.buddies.map(b=>`<div class="buddy"><b>${b.name}</b><div class="progress"><span style="width:${b.progress}%"></span></div><span>🔥 ${b.streak} days</span></div>`).join(''):'<p class="muted">No buddies yet. Add a study buddy to see safe streaks.</p>'}
function checkIn(){const c=child();c.streak=(c.streak||0)+1;save();toast('Checked in today')}
function completePractice(){child().weekly=Math.min(100,(child().weekly||0)+6);save();toast('Practice round completed')}
function loadDemo(){state=structuredClone(emptyState);state.homework=[{child:'Student A',subject:'Math',title:'Worksheet Q1-Q8',date:'Tomorrow · 8 Jul',done:false},{child:'Student A',subject:'English',title:'Vocabulary review',date:'Fri · 10 Jul',done:false}];state.exams=[{child:'Student A',subject:'Science',title:'Project submission',date:'17 Jul',done:false}];state.schedule=[{child:'Student A',title:'Math tuition',date:'Wednesday 5:00 PM'}];state.buddies=[{name:'Study Buddy 1',streak:4,progress:48},{name:'Study Buddy 2',streak:7,progress:72}];state.children[0].streak=5;state.children[0].weekly=72;state.children[0].todayDone=2;state.children[1].streak=3;state.children[1].weekly=55;save();toast('Demo loaded');go('student')}
function progressPct(){const hw=state.homework.filter(h=>h.child===state.activeChild);const wk=state.weekly.filter(h=>h.child===state.activeChild);return{homework:hw.length?Math.round(hw.filter(h=>h.done).length/hw.length*100):0,weekly:wk.length?Math.round(wk.filter(h=>h.done).length/wk.length*100):(child().weekly||0)}}
function showModal(html){document.getElementById('modalContent').innerHTML=html;document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function val(id){return document.getElementById(id)?.value.trim()||''}
renderAll();
